# Generated by Django 5.1.2 on 2024-12-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecameras', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='stream_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='description',
        ),
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
