# Generated by Django 5.1.2 on 2024-12-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecameras', '0002_rename_stream_url_camera_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='url',
            new_name='stream_url',
        ),
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
