# Generated by Django 5.1.2 on 2025-01-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecameras', '0003_rename_url_camera_stream_url_alter_camera_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screenshots/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
