# Generated by Django 5.1.2 on 2025-01-28 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecameras', '0004_screenshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Screenshot',
        ),
        migrations.RenameField(
            model_name='camera',
            old_name='stream_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='camera',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to=settings.AUTH_USER_MODEL),
        ),
    ]
