# Generated by Django 5.1.2 on 2025-04-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homecameras', '0012_saverecords'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaveRecords',
        ),
    ]
